### ISSUE TITLE
Cant not use @if or @foreach in blade 

### ISSUE THREAD

**Issue by lchhieu** [spatie/laravel-database-mail-templates#12]
I'm trying to use @if or @foreach but it doesn't seem to work

`@if (count($records) === 1)
    I have one record!
@elseif (count($records) > 1)
    I have multiple records!
@else
    I don't have any records!
@endif
`

**Comment by fbingha** [comment]
From what I see in my test, blade statements are not parsed in this package.

**Comment by ju5t** [comment]
Out of curiosity, is there any reason why this issue was immediately closed? It would be very useful for us if we could use foreach in an email template (e.g. an order confirmation with multiple lines).

**Comment by ju5t** [comment]
@freekmurze sorry to tag you in this, but would you mind having a look at my question?

What would be a sane alternative to `@if`-statements in an e-mail? Let's say we have an order confirmation that includes a line of text depending on the chosen payment method. How would we do this? 

We don't want to rewrite the entire e-mail but having this text in 'code' kind of defeats the purpose of storing emails in a database, I think.

I'm open for any suggestions and yes, once the application that's going to use this is ready, we'll send you a postcard, no worries :-)

**Comment by ju5t** [comment]
hi @AlexVanderbist, I hope you have some time to look into this. I think because the issue is closed, it doesn't pop up as things to do in this package.

**Comment by bushbill** [comment]
For all coming here... please see this: https://github.com/bobthecow/mustache.php/wiki/Mustache-Tags

This package uses Mustache Templates and there is something like an "if-statement" and "records".

{{# condition }}
{{ value }}
{{/ condition }}
