### ISSUE TITLE
Template wont use HTML tags

### ISSUE THREAD

**Issue by PetraBencek** [spatie/laravel-database-mail-templates#15]
So when I use the {{ body }} tag in my main.html file which is my template it just shows plain text and does not support HTML tags. Example: `<b>Sample</b>` instead of **Sample**

**Comment by AlexVanderbist** [comment]
Hey! Under the hood we use Mustache to parse the templates. Instead of blades `{!! $variable !!}` syntax, they use `{{{ variable }}}` for unescaped output.

tl;dr: use `{{{ body }}}`

Good luck!

**Comment by fbingha** [comment]
What is the effort level to get the template parsed by the blade engine?
