### ISSUE TITLE
Dynamically setup template variables when extending the Model

### ISSUE THREAD

**Issue by matthaselip** [spatie/laravel-database-mail-templates#29]
Hi

Is there a way to dynamically set the template variables from the model?  for example using Magic methods __set() and __get()  allow me to retrieve properties from a properties array?

**Comment by stfr** [comment]
Did you find a solution ?
__set & __get didn't work, because variables are build from ReflectionClass. So.... if your property doesn't exist in class declaration or __construct, you can't define it.

**Comment by matthaselip** [comment]
Hi, no ive not got this to work,

**Comment by matthaselip** [comment]
also having problems declaring template variables when extending a custom mail class, i assume that the variables in the parent class are available when extending only

**Comment by stfr** [comment]
I managed to did it by extending the TemplateMailable with my homemade TemplateMailable. After that, i redefined a few methods, and it works. My goal was to generate and use auto-generated tags from various objects, in order to factorise  things like that : 
```
Mail::to($user->email)
     ->send((new WelcomeEmail($user->id))
     ->addTagObject($company)
     ->addManualTag('link', $link)
```

I can use all tags generated from $company object without defining them in my WelcomeEmail class. (and use the same in other Mailable class too :) )

I can share the class if needed ;)

**Comment by thdebay** [comment]
Hi @stfr, I'm interested in seeing your code if you don't mind sharing it with me. I'm trying to achieve various customization of the `TemplateMailable` class (to allow Blade or php directives within the mail template, and to pass more variables as you did). Your code might give me some hints to move forward. Thank you!

**Comment by Restingo** [comment]
> I managed to did it by extending the TemplateMailable with my homemade TemplateMailable. After that, i redefined a few methods, and it works. My goal was to generate and use auto-generated tags from various objects, in order to factorise things like that :
> 
> ```
> Mail::to($user->email)
>      ->send((new WelcomeEmail($user->id))
>      ->addTagObject($company)
>      ->addManualTag('link', $link)
> ```
> 
> I can use all tags generated from $company object without defining them in my WelcomeEmail class. (and use the same in other Mailable class too :) )
> 
> I can share the class if needed ;)

Can you please share your code? Thank you.

**Comment by stfr** [comment]
@Restingo i'm currently on holidays, but i will share it monday ;)

**Comment by Restingo** [comment]
@stfr thank you and nice holidays! 💯

**Comment by Restingo** [comment]
@stfr friendly reminder :smiley:

**Comment by stfr** [comment]
@Restingo Here is a quick repo with my custom classes : 
https://github.com/stfr/spatie-permission-tagmanager-example

You can find how i use it in the README.md

Interesting files are : 

app\Mails\SampleEmail.php => The mailable class, where i define tags for this email.
app\Mails\TagManagerMailable.php  => My extension of the Spatie Mailable, where the magic is done.
app\Helpers\TagManagerHelper.php => Where you can create your tags.
