### ISSUE TITLE
html print instead of render

### ISSUE THREAD

**Issue by rashidhussainshah** [spatie/laravel-database-mail-templates#41]
eodHtmlTemplate print html instead of rendering 
EodMail.php
`<?php

namespace App\Mail;

use App\Models\Project;
use Illuminate\Bus\Queueable;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Mail\Mailable;
use Illuminate\Queue\SerializesModels;
use Spatie\MailTemplates\TemplateMailable;

class EodMail extends TemplateMailable
{
    use Queueable, SerializesModels;

    /** @var string */
    public $name;

    /** @var string */
    public $eodHtmlTemplate;

    public function __construct(Project $project, $eodHtmlTemplate)
    {
        $this->name = $project->eodConfiguration->client->name;
        $this->eodHtmlTemplate = $eodHtmlTemplate;
    }

    public function getHtmlLayout(): string
    {
        /**
         * In your application you might want to fetch the layout from an external file or Blade view.
         *
         * External file: `return file_get_contents(storage_path('mail-layouts/main.html'));`
         *
         * Blade view: `return view('mailLayouts.main', $data)->render();`
         */

        return view('mail-layouts.eod')->render();

//        return '<header>Site name!</header>{{{ body }}}<footer>Copyright 2018</footer>';
    }

}
`
eod.blade.php
`Hi
<br>
@{{{body}}}
<p>Copyright 2022</p>`

Send Email
 Mail::to($project->eodConfiguration->client->email)->send(new EodMail($project, $request->email));

![image](https://user-images.githubusercontent.com/39673127/159127055-2474fee6-1f23-4d45-a9fc-9d35aa7d6f66.png)

 if I try to use {!! eodHtmlTemplate !!}

![image](https://user-images.githubusercontent.com/39673127/159127087-18e9a150-a264-422e-b36b-8841de5d2ee9.png)

**Comment by mrengineer19** [comment]
Did you able to solve this?
