### ISSUE TITLE
Minimum Laravel version

### ISSUE THREAD

**Issue by mohinlakdawala** [spatie/laravel-database-mail-templates#6]
Hello, 

I see the package has listed Laravel 5.7 as one of the requirements? Does it use any 5.7 specific feature? If not, can this be installed on previous Laravel versions like 5.5?

Thanks
Mohin

**Comment by freekmurze** [comment]
We only need this to work on L5.7 so we didn't invest time to research if it is compatible with L5.5.

If these tests pass on L5.5 and there aren't any modifications needed to the code at all, I'd welcome a PR that allows L5.5, L5.6 (and testbench 3.5, 3.6) in `composer.json`.
