### ISSUE TITLE
Using blade as a layout

### ISSUE THREAD

**Issue by inet123** [spatie/laravel-database-mail-templates#8]
Hi,

I'm trying to use a blade file as a template, but I'm not sure how to integrate `{{{ body }}}` inside the blade layout. Whatever I do I keep getting an error message `Use of undefined constant body - assumed 'body'` and if I try to replace it with a $body I get an unknown variable error.

This is my code:
`
    public function getLayout(): string {
        return view('emails.base')->render();
    }
`
Edit: I was able to find a work-around by putting some other magic text and then replacing it after the render, but when trying to use components in blade (specificly `@component('mail::message')`) I'm getting the error - `No hint path defined for [mail]`

Thank you.

**Comment by davemorris80** [comment]
Can we update the main documentation with this pls.

**Comment by simonbuehler** [comment]
> ... but when trying to use components in blade (specificly `@component('mail::message')`) I'm getting the error - `No hint path defined for [mail]`

hi,

i have the same issue (No hint path defined for [mail].)  when using components in the blade file.

```php
public function getHtmlLayout(): string
    {
        /**
         * In your application you might want to fetch the layout from an external file or Blade view.
         *
         * External file: `return file_get_contents(storage_path('mail-layouts/main.html'));`
         *
         * Blade view: `return view('mailLayouts.main', $data)->render();`
         */

        return view('emails.contact')->render();
    }
```

and contact.blade.php

```php
@component('mail::message')
# Introduction

The body of your message.
@{{{ $body }}}
@component('mail::button', ['url' => ''])
Button Text
@endcomponent

Thanks,<br>
{{ config('app.name') }}
@endcomponent
```


@idoadiv did you get this working?

**Comment by oceceli** [comment]
@simonbuehler Have you found a solution? (No hint path defined for [mail].)

**Comment by Beaudinn** [comment]
@oceceli Here you go 

	public function getHtmlLayout(): string
	{

		$markdown = app(Markdown::class);

		return $markdown->render('mail.layout', [])->toHtml();
	}
