### ISSUE TITLE
MailTemplate doesn't work in a nova resource properly

### ISSUE THREAD

**Issue by fbingha** [spatie/laravel-database-mail-templates#9]
When using MailTemplate as the basis model of a Nova Resource, the create flow breaks due the the subject and template functions.

Nova doesn't work properly when an attribute and a model have the same name.

Could you change the subject and template method names to getSubject and getTemplate?

**Comment by freekmurze** [comment]
Feel free to submit a non-breaking, well tested PR that fixes this.
